Repository TeamRecorDream/RecorDream-iOS, pull requests merged in 2022-10, with the labels that each got.

#24 [Feat] #19 - 음성 녹음 뷰 구현하기
  RecorDream-iOS/Projects/Core/Sources/Foundation+/Int+.swift
  RecorDream-iOS/Projects/Core/Sources/UIKit+/UIApplication+.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Derived/Sources/TuistAssets+RDDSKit.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/DreamWrite/VoiceRecordView/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/DreamWrite/VoiceRecordView/icn_mic_title.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/DreamWrite/VoiceRecordView/icn_mic_title.imageset/icn_mic_title.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/DreamWrite/VoiceRecordView/icn_mic_title.imageset/icn_mic_title@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/DreamWrite/VoiceRecordView/icn_mic_title.imageset/icn_mic_title@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWritePlayerSliderView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteRecordView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDSlider/DreamWriteSlider.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteMainCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 록시보이 🌽, feat

#26 [Style] #20 - 검색 뷰 UI 잡기
  RecorDream-iOS/Projects/Core/Sources/UIKit+/UITextField+.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDView/DreamGenreView.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/DreamSearhControllable.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchBottomCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchCountCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchEmptyCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchExistCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchSection.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchViewModel.swift
Labels: 으니짱 🍅, feat

#25 [Feat] #14 - 네트워크 레이어 구현 및 클린아키텍쳐 예시코드 작성
  .gitignore
  RecorDream-iOS/Projects/Core/Sources/Util/JsonCoder.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DTO/DreamWriteDTO.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/.gitkeep
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamWriteTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamWriteRepository.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultMyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWriteEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamWriteUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/DependencyContainer.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/API/.gitkeep
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/API/Sample.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/GeneralResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/HeaderType.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/NetworkResult.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/AFManager.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/EventMonitor.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/Interceptor.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/DreamWriteResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/AuthRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/NoticeRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/RecordRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/UserRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/VoiceRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/AuthService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/NoticeService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/UserService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/VoiceService.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
Labels: 록시보이 🌽
