Repository TeamRecorDream/RecorDream-iOS, pull requests merged in 2022-12, with the labels that each got.

#49 [Feat] #42 - 작성하기 뷰 API 연결
  RecorDream-iOS/Projects/Core/Sources/Foundation+/String+.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWrite/DreamWriteRequest.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamWriteUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteRecordView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/MainTabBarCoordinator.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/HeaderType.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/DreamWriteResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/AuthRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/NoticeRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/RecordRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/UserRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/VoiceRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/VoiceService.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
Labels: 록시보이 🌽, feat

#60 [Feat] #56 - RxTest, Nimble, Quick 의존성 추가 및 테스트 코드 샘플
  RecorDream-iOS/Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  RecorDream-iOS/Projects/Core/Derived/InfoPlists/RD-CoreTests-Info.plist
  RecorDream-iOS/Projects/Core/Tests/CoreTests.swift
  RecorDream-iOS/Projects/Data/Project.swift
  RecorDream-iOS/Projects/Data/Tests/MyPageRepositoryTests.swift
  RecorDream-iOS/Projects/Domain/Project.swift
  RecorDream-iOS/Projects/Domain/Tests/Mock/MockMyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Tests/MyPageUseCaseTests.swift
  RecorDream-iOS/Projects/Modules/RD-Analytics/Derived/InfoPlists/RD-AnalyticsTests-Info.plist
  RecorDream-iOS/Projects/Modules/RD-DSKit/Project.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Tests/DSKitTests.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Tests/DesignSystemTests.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Derived/InfoPlists/RD-NavigatorTests-Info.plist
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Tests/RD-NavigatorTests.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Project.swift
  RecorDream-iOS/Projects/Modules/RD-User/Derived/InfoPlists/RD-UserTests-Info.plist
  RecorDream-iOS/Projects/Modules/RD-User/Tests/RD-UserTests.swift
  RecorDream-iOS/Projects/Modules/RD-UtilKit/Derived/InfoPlists/RD-UtilKitTests-Info.plist
  RecorDream-iOS/Projects/Modules/RD-UtilKit/Tests/RD-UserTests.swift
  RecorDream-iOS/Projects/Modules/ThirdPartyLib/Derived/InfoPlists/ThirdPartyLibTests-Info.plist
  RecorDream-iOS/Projects/Modules/ThirdPartyLib/Tests/.gitkeep
  RecorDream-iOS/Projects/Presentation/Project.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/ViewModel/MyPageViewModel.swift
  RecorDream-iOS/Projects/Presentation/Tests/Mock/MockMyPageUseCase.swift
  RecorDream-iOS/Projects/Presentation/Tests/MyPageViewModelTest.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOSTests-Info.plist
  RecorDream-iOS/Projects/RecorDream-iOS/Tests/.gitkeep
  RecorDream-iOS/Tuist/Dependencies.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/Environment.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  RecorDream-iOS/graph.png
Labels: 록시보이 🌽, feat, test

#53 [Feat] #50 - 로그인・스플래쉬 뷰 UI 구성 및 API 연결, 자동 로그인 기능 구현
  RecorDream-iOS/Projects/Core/Sources/Constants/C.swift
  RecorDream-iOS/Projects/Core/Sources/Constants/Key.swift
  RecorDream-iOS/Projects/Core/Sources/Protocols/UserDefaultManager.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamSearchResuest.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultAuthRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Auth/AuthEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Auth/AuthRequest.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/AuthRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/AuthUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Derived/Sources/TuistAssets+RDDSKit.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/Kakaotalk.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/Kakaotalk.imageset/Kakaotalk.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/Kakaotalk.imageset/Kakaotalk@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/Kakaotalk.imageset/Kakaotalk@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/apple.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/apple.imageset/apple.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/apple.imageset/apple@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/apple.imageset/apple@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDButton/RDLoginButton.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/AuthResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/AuthRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/AuthService.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/View/LoginVC+Network.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/View/LoginVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/ViewModel/LoginViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/AuthControllable.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/AuthView.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/SplashVC.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/AppDelegate.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/SceneDelegate.swift
Labels: 으니짱 🍅, feat

#62 [Add] Lottie 라이브러리 의존성 추가
  RecorDream-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  RecorDream-iOS/Tuist/Dependencies.swift
Labels: suvera 🥦, set

#52 [Feat] 홈 뷰 Data & Domain Layer 구현
  RecorDream-iOS/Projects/Data/Sources/Network/DTO/HomeDTO.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/HomeDataTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultHomeRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Home/HomeEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/HomeEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/HomeRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/HomeUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/HomeViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/Cell/DreamCardCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/DreamCardCollectionViewAdapter.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MainTabBar/MainTabBarController.swift
Labels: suvera 🥦, feat

#64 [Feat] #48 - 전체적인 플로우 연결, 유저 플로우 리팩토링, 마이페이지 API 연결
  RecorDream-iOS/Projects/Core/Sources/Constants/Constants.swift
  RecorDream-iOS/Projects/Core/Sources/Constants/UserDefaultKey.swift
  RecorDream-iOS/Projects/Core/Sources/Protocols/UserDefaultManager.swift
  RecorDream-iOS/Projects/Core/Sources/UIKit+/UIApplication+.swift
  RecorDream-iOS/Projects/Core/Sources/UIKit+/UIWindow+.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/UserInfoTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Network/Mock/.gitkeep
  RecorDream-iOS/Projects/Data/Sources/Network/Mock/SampleMock.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultAuthRepository.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultMyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Auth/AuthEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/AuthRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/MyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/AuthUseCase.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/MyPageUseCase.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/UseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamLogoView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/RDDateTimePickerView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDNaviBar/RDNaviBar.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/MainTabBarCoordinator.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/DependencyContainer.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/GeneralResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Environment/HeaderType.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Auth/AuthResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Record/DreamSearchResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Record/DreamWriteResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/User/ChangeNoticeStatusResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/User/ReissuanceResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/User/UserInfoResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/AuthRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/NoticeRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/UserRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/AuthService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/NoticeService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/UserService.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/View/LoginVC+Network.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/View/LoginVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/ViewModel/LoginViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/SplashVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/HomeViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MainTabBar/MainTabBarController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/View/MyPageVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/ViewModel/MyPageViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/StorageVC.swift
  RecorDream-iOS/Projects/Presentation/Tests/Mock/MockMyPageUseCase.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/AppDelegate.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/SceneDelegate.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: 록시보이 🌽, feat

#66 [Feat] 꿈 카드 상세보기 뷰 UI 구현
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamDetailRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamDetail/DreamDetailEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamDetailRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamDetailUseCase.swift
  RecorDream-iOS/Projects/DreamDetailEntity.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Derived/Sources/TuistAssets+RDDSKit.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_blue.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_blue.imageset/card_m_blue-1.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_blue.imageset/card_m_blue@2x-1.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_blue.imageset/card_m_blue@3x-1.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_purple.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_purple.imageset/card_m_blue.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_purple.imageset/card_m_blue@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/card_m_purple.imageset/card_m_blue@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/icn_more.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/icn_more.imageset/icn_mpre.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/icn_more.imageset/icn_mpre@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/icn_more.imageset/icn_mpre@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamAudioPlayerView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamDetailHeaderView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Home/DreamLogoView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDView/DreamGenreTagView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Constants/Factory/Card/DreamCardType.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/DreamDetailViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DetailRecordPageViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamNoteViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamRecordViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/RDSegmentedControl.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/Cell/DreamCardCVC.swift
Labels: suvera 🥦, feat

#65 [Feat] #63 - 로딩 기능 구현 및 작성하기, 마이페이지에 연결
  RecorDream-iOS/Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamWriteUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/mainLoading.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/RDDateTimePickerView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDLoading/RDLoading+UIViewController.swift
  RecorDream-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/SplashVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/View/MyPageVC.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Tuist/Dependencies.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: 록시보이 🌽, feat

#72 [Feat] #71 - 푸시 알림 변경 및 닉네임 변경 에러 수정
  RecorDream-iOS/Projects/Domain/Sources/UseCases/MyPageUseCase.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/ViewModel/MyPageViewModel.swift
Labels: 록시보이 🌽, fix

#75 [Feat] #43 - 검색 뷰 Business Logic 수정 및 API 연결
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamSearchTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultSearchRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamSearch/DreamSearchEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamSearch/DreamSearchQuery.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DremSearchRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamSearchUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Home/DreamLogoView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDTextField/DramSearchTextField.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Constants/Control/RDControllable.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Record/DreamSearchResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/RecordRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/AuthView.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/SplashVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/Cell/StorageEmptyCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/Cell/StorageExistCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/Cell/StorageHeaderCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/StorageVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/DreamSearhControllable.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchBottomCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchEmptyCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchExistCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchHeaderCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchCompositionalLayout.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchSection.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchResultViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchViewModel.swift
Labels: 으니짱 🍅, feat

#76 [Feat] #74 - 수정하기 기능 구현 및 분기처리
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamWriteTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWrite/DreamWriteEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWrite/DreamWriteRequest.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamWriteUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDTextView/DreamWriteTextView.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseService.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Record/DreamWriteModifyResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/RecordRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteMainCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
Labels: 록시보이 🌽

#79 [Fix] #78 - 검색 뷰 데이터 바인딩 오류 수정
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamSearchTransform.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamSearch/DreamSearchEntity.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDTextField/DramSearchTextField.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchCompositionalLayout.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
Labels: 록시보이 🌽, fix

#83 [Feat] 상세보기 추가 기능 Bottom sheet UI 구현
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamDetailMoreRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamDetail/DreamDetailMoreEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamDetailMoreRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamDetailMoreUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamDetailHeaderView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/StorageVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/SceneDelegate.swift
Labels: suvera 🥦, feat

#86 [Feat] #73 - Push 알림 탭 시 작성하기로 화면전환
  RecorDream-iOS/Projects/Core/Sources/Constants/UserDefaultKey.swift
  RecorDream-iOS/Projects/Core/Sources/Protocols/UserDefaultManager.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/PushNoticeCoordinatable.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+PushNoticeCoordinatable.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/AppDelegate.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/SceneDelegate.swift
Labels: feat
