Repository TeamRecorDream/RecorDream-iOS, pull requests merged in 2022-11, with the labels that each got.

#32 [Feat] #31 - 작성하기 뷰 비즈니스 로직 및 데이터 바인딩
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamWriteTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultDreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWrite/DreamWriteEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWrite/DreamWriteRequest.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamWriteEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DreamWriteRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamWriteUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDButton/DreamWriteSaveButton.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDSupplementaryView/DreamWriteWarningFooter.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDTextView/DreamWriteTextView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/MainTabBarCoordinator.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteEmotionCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteMainCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteNoteCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/SampleScene/Sample/View/StartViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/SampleScene/Sample/ViewModel/Feature.swift
  RecorDream-iOS/Projects/Presentation/Sources/SampleScene/SampleSceneDICoordinator.swift
Labels: 록시보이 🌽, feat

#34 [Feat] #30 - APNs 세팅 및 테스트
  .gitignore
  RecorDream-iOS/Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  RecorDream-iOS/Plugin/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  RecorDream-iOS/Projects/Modules/ThirdPartyLib/Project.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Projects/RecorDream-iOS/Project.swift
  RecorDream-iOS/Projects/RecorDream-iOS/RecorDream-iOS.entitlements
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/AppDelegate.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Sources/Applications/SceneDelegate.swift
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 록시보이 🌽, feat

#35 [Feat] #33 - 마이페이지 Domain 및 Data 구현
  RecorDream-iOS/Plugin/UtilityPlugin/ProjectDescriptionHelpers/SettingsDictionary+.swift
  RecorDream-iOS/Projects/Core/Sources/Util/makeAlert.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultMyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/MyPage/MyPageEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/MyPageEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/MyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/MyPageUseCase.swift
  RecorDream-iOS/Projects/Domain/Tests/MyPageUseCaseTests.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/MyPageEditableView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/MyPageInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/RDDateTimePickerView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/MainTabBarCoordinator.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/View/MyPageVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/ViewModel/MyPageViewModel.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  RecorDream-iOS/Projects/RecorDream-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 록시보이 🌽, feat

#38 [FEAT] 홈 전체 UI 구현
  RecorDream-iOS/Projects/Core/Sources/Foundation+/Array+.swift
  RecorDream-iOS/Projects/Core/Sources/Util/CGFloat+.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DTO/HomeDTO.swift
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultHomeRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/HomeEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/HomeRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/HomeUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Derived/Sources/TuistAssets+RDDSKit.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_home_logo.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_home_logo.imageset/rd_home_rogo.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_home_logo.imageset/rd_home_rogo@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_home_logo.imageset/rd_home_rogo@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_splash_logo.imageset/Contents.json
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_splash_logo.imageset/rd_splash_rogo.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_splash_logo.imageset/rd_splash_rogo@2x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Resources/Images.xcassets/rd_splash_logo.imageset/rd_splash_rogo@3x.png
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamLogoView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDView/DreamGenreTagView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Constants/Factory/Font/TypoStyle+.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Constants/Factory/Font/TypoStyle.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/HomeResponse.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/HomeViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/Cell/DreamCardCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/DreamCardCollectionViewAdapter.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MainTabBar/MainTabBarController.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchBottomCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchSection.swift
Labels: suvera 🥦, feat

#37 [Feat] #36 - 마이페이지 시간 설정 기능 비즈니스 로직 구현
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultMyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/MyPageRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/MyPageUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/MyPageInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/RDDateTimePickerView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/Coordinators/MainTabBarCoordinator.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/View/MyPageVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/MyPage/ViewModel/MyPageViewModel.swift
Labels: 록시보이 🌽, feat

#39 [WIP] 검색 뷰 기능 구현 및 아키텍처 적용
  RecorDream-iOS/Projects/Core/Sources/Protocols/Cancellable.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/DreamSearchResuest.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamSearch/DreamSearchEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/DreamSearch/DreamSearchQuery.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/DremSearchRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/DreamSearchUseCase.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/UseCase.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/DreamSearchResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/RecordRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/DreamSearhControllable.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchBottomCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchCountCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchExistCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/Layout/DreamSearchSection.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchResultViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchViewModel.swift
  RecorDream-iOS/Tuist/Dependencies.swift
Labels: 으니짱 🍅, feat, fix

#46 [Fix] #45 - 미완성 코드 주석처리
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/RecordService.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/DreamSearhControllable.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchBottomCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/Cell/DreamSearchCountCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/View/DreamSearchVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/SearchScene/DreamSearch/ViewModel/DreamSearchViewModel.swift
Labels: 으니짱 🍅, fix

#47 [Feat] #18 - 날짜 설정 뷰 커스텀 / #44 - 녹음 및 날짜 선택 기능 작성하기 뷰 UI에 binding
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteInteractionView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWritePlayerSliderView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/DreamWriteRecordView.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/RDDateTimePickerView.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/CollectionViewCell/DreamWriteMainCVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/View/DreamWriteVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamWrite/ViewModel/DreamWriteViewModel.swift
Labels: 록시보이 🌽, feat
