Repository TeamRecorDream/RecorDream-iOS, pull requests merged in 2023-02, with the labels that each got.

#139 [Feat] 인스타 공유 로직 구현
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamShareView.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/Factory/ViewControllerFactory.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/DreamDetailViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreViewModel.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/Share/DreamShareView.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/Share/DreamShareViewModel.swift
  RecorDream-iOS/Projects/RecorDream-iOS/Derived/InfoPlists/RecorDream-iOS-Info.plist
  RecorDream-iOS/Tuist/ProjectDescriptionHelpers/BaseInfoPlist.swift
Labels: suvera 🥦, feat

#142 [Feat] #140 - 홈, 상세보기 GA
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamAudioPlayerView.swift
  RecorDream-iOS/Projects/Modules/RD-Logger/Sources/EventType/LogEventType.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DetailRecordPageViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/HomeVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Storage/View/Cell/StorageExistCVC.swift
Labels: suvera 🥦, set

#143 [Feat] 음성녹음만 있는 경우 Empty View 처리
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/HomeDataTransform.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Home/HomeEntity.swift
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Home/VoiceNoticeView.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Record/HomeDreamResponse.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/Home/View/CollectionView/Cell/DreamCardCVC.swift
Labels: suvera 🥦, feat

#146 [Feat] #145 - 강제 업데이트 & 권장 업데이트 플로우 구현
  RecorDream-iOS/Projects/Core/Sources/Constants/UserDefaultKey.swift
  RecorDream-iOS/Projects/Core/Sources/Foundation+/Bundle+.swift
  RecorDream-iOS/Projects/Core/Sources/Foundation+/URL+.swift
  RecorDream-iOS/Projects/Core/Sources/Protocols/UserDefaultManager.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/.gitkeep
  RecorDream-iOS/Projects/Data/Sources/DataTransform/DreamDetailDataTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/DreamSearchTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/DreamStorageTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/DreamWriteTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/HomeDataTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/UserInfoTransform.swift
  RecorDream-iOS/Projects/Data/Sources/DataTransform/VersionCheckTransform.swift
  RecorDream-iOS/Projects/Data/Sources/Network/DataTransform/.gitkeep
  RecorDream-iOS/Projects/Data/Sources/Repositories/DefaultAuthRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/Entities/Auth/VersionCheckEntity.swift
  RecorDream-iOS/Projects/Domain/Sources/RepositoryInterfaces/AuthRepository.swift
  RecorDream-iOS/Projects/Domain/Sources/UseCases/AuthUseCase.swift
  RecorDream-iOS/Projects/Modules/RD-Navigator/Sources/DependencyContainer/FactoryImpl/DependencyContainer+ViewControllerFactory.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Responses/Auth/VersionResponse.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Routers/AuthRouter.swift
  RecorDream-iOS/Projects/Modules/RD-Network/Sources/Services/AuthService.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/View/SplashVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Splash/ViewModel/SplashViewModel.swift
Labels: feat

#144 [Feat] 녹음 관련 QA - 무음모드, 재생 중지 + etc) 검색어 볼드 처리
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamAudioPlayerView.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamRecordViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreVC.swift
Labels: suvera 🥦, fix

#148 [Fix] #147 - 상세보기 GA 경로 수정
  RecorDream-iOS/Projects/Modules/RD-DSKit/Sources/Components/RDCustomView/Detail/DreamAudioPlayerView.swift
  RecorDream-iOS/Projects/Modules/RD-Logger/Sources/EventType/LogEventType.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DetailRecordPageViewController.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
  RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetailMore/DreamDetailMoreVC.swift
Labels: 으니짱 🍅, fix

#150 [Edit] #149 - kakaoLoginButton topAnchor 조정
  RecorDream-iOS/Projects/Presentation/Sources/AuthScene/Auth/View/LoginVC.swift
Labels: 으니짱 🍅, fix
